// Applies the site-wide SEO and analytics head fragments to every hand-authored
// page, then leaves a marker so re-running is a no-op.
//
// Three things were missing across the 63 indexable pages:
//   1. no audience measurement at all - the GA4 property only existed on /blog/,
//      so the homepage, the 32 articles and the 29 tools reported nothing;
//   2. no BreadcrumbList, so Search had no trail to show under a result;
//   3. the brand logo link exposed no accessible name, which is both an a11y
//      failure and an internal link Google cannot label.
//
// Article pages are regenerated by articles/build-articles.mjs, which emits the
// same fragments from pageShell(); this script is what covers the hand-authored
// tool pages, the two homepages and 404.html.
//
// Run: node build-seo.mjs
import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const ROOT = process.cwd();
const SITE = "https://benoit-gaumard.io";
export const GA4_ID = "G-75X1Q2PPLE";
const SKIP = new Set(["blog", "public", "node_modules", "themes", ".git", ".github", ".impeccable", ".playwright-mcp", "favicons"]);

// The anchor is the one line every page shares verbatim, hand-authored and
// generated alike. Injecting after it puts gtag high in <head> without landing
// before charset/viewport.
const ANCHOR = '<meta name="color-scheme" content="light">';
const MARKER = "<!-- seo:analytics -->";

export function analyticsSnippet(indent = "  ") {
  return [
    `${indent}${MARKER}`,
    // Consent Mode v2 defaults lead the block: they have to be queued before
    // gtag.js loads, otherwise the tag reads a personalised default first.
    // Kept byte-identical to ANALYTICS_SNIPPET in articles/build-articles.mjs.
    `${indent}<script>`,
    `${indent}  window.dataLayer = window.dataLayer || [];`,
    `${indent}  function gtag(){dataLayer.push(arguments);}`,
    `${indent}  gtag('consent', 'default', {`,
    `${indent}    ad_storage: 'denied',`,
    `${indent}    ad_user_data: 'denied',`,
    `${indent}    ad_personalization: 'denied',`,
    `${indent}    analytics_storage: 'denied',`,
    `${indent}    functionality_storage: 'granted',`,
    `${indent}    security_storage: 'granted',`,
    `${indent}    wait_for_update: 500`,
    `${indent}  });`,
    `${indent}  gtag('set', 'ads_data_redaction', true);`,
    `${indent}  gtag('set', 'url_passthrough', true);`,
    `${indent}</script>`,
    `${indent}<script async src="https://www.googletagmanager.com/gtag/js?id=${GA4_ID}"></script>`,
    `${indent}<script>`,
    `${indent}  gtag('js', new Date());`,
    `${indent}  gtag('config', '${GA4_ID}');`,
    `${indent}</script>`,
  ].join("\n");
}

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith(".") || SKIP.has(entry)) continue;
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (entry.endsWith(".html")) out.push(p);
  }
  return out;
}

function urlFor(path) {
  const rel = relative(ROOT, path).split(sep).join("/");
  if (rel === "index.html") return "/";
  return "/" + rel.replace(/index\.html$/, "");
}

// A breadcrumb that does not mirror a trail the visitor can actually see is
// exactly the kind of markup Google treats as misleading, so this only emits a
// Tools crumb for pages that really render the "All tools" link.
export function breadcrumbFor(url, title, html) {
  if (url === "/" || url === "/index_fr.html") return null;
  const items = [{ name: "Home", item: `${SITE}/` }];
  if (url.startsWith("/articles/") && url !== "/articles/") {
    items.push({ name: "Articles", item: `${SITE}/articles/` });
  } else if (html.includes('href="/tools/"') && url !== "/tools/") {
    items.push({ name: "Tools", item: `${SITE}/tools/` });
  }
  items.push({ name: title, item: `${SITE}${url}` });
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((entry, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: entry.name,
      item: entry.item,
    })),
  };
}

function titleOf(html) {
  const m = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  if (!m) return null;
  return m[1].replace(/\s*\|\s*Benoit Gaumard\s*$/, "").replace(/\s+/g, " ").trim();
}

function injectAnalytics(html) {
  const eol = html.includes("\r\n") ? "\r\n" : "\n";

  // A block written before Consent Mode was added carries the marker but no
  // consent defaults, so a plain marker check would leave it personalising by
  // default forever. Rewrite it in place instead of skipping it.
  if (html.includes(MARKER)) {
    if (html.includes("gtag('consent', 'default'")) return html;
    const block = new RegExp(
      `([ \\t]*)${MARKER}[\\s\\S]*?gtag\\('config', '${GA4_ID}'\\);[\\s\\S]*?<\\/script>`
    );
    const m = html.match(block);
    if (!m) return html;
    return html.replace(block, analyticsSnippet(m[1]).split("\n").join(eol));
  }

  const i = html.indexOf(ANCHOR);
  if (i === -1) return null;
  const indent = (html.slice(0, i).match(/([ \t]*)$/) || ["", "  "])[1];
  const snippet = analyticsSnippet(indent).split("\n").join(eol);
  return html.slice(0, i + ANCHOR.length) + eol + snippet + html.slice(i + ANCHOR.length);
}

// AdSense requires a privacy policy reachable from every page, and the footer
// is the one element every hand-authored page shares.
function addPrivacyLink(html) {
  if (html.includes('href="/privacy/"')) return html;
  const marker = '<span>&copy; <span id="currentYear"></span> Benoit Gaumard</span>';
  if (!html.includes(marker)) return html;
  const eol = html.includes("\r\n") ? "\r\n" : "\n";
  return html.replace(marker, `${marker}${eol}        <a href="/privacy/">Privacy &amp; cookies</a>`);
}

function addFooterLinkStyles(html) {
  if (html.includes(".footer-bottom a {")) return html;
  const anchor = `${html.includes("\r\n") ? "\r\n" : "\n"}    .back-to-top {`;
  if (!html.includes(anchor)) return html;
  const eol = html.includes("\r\n") ? "\r\n" : "\n";
  const css = [
    `    .footer-bottom a { color: var(--cp-text-muted); text-decoration: none; }`,
    `    .footer-bottom a:hover { color: var(--cp-link); }`,
    ``,
    `    .back-to-top {`,
  ].join(eol);
  return html.replace(anchor, eol + css);
}

function injectBreadcrumb(html, url) {
  if (html.includes('"BreadcrumbList"')) return html;
  const title = titleOf(html);
  if (!title) return html;
  const crumb = breadcrumbFor(url, title, html);
  if (!crumb) return html;
  const close = html.lastIndexOf("</head>");
  if (close === -1) return html;
  const eol = html.includes("\r\n") ? "\r\n" : "\n";
  const body = JSON.stringify(crumb, null, 2).split("\n").map((l) => `  ${l}`).join(eol);
  const block = [`  <script type="application/ld+json">`, body, `  </script>`].join(eol);
  return html.slice(0, close) + block + eol + html.slice(close);
}

// Browsers request /favicon.ico at the domain root whether or not it is
// declared, but declaring it makes the fallback explicit for clients that do
// not take the SVG, and keeps the ICO ahead of it in source order.
function addIcoLink(html) {
  if (html.includes('href="/favicon.ico"')) return html;
  return html.replace(
    /([ \t]*)<link rel="icon" type="image\/svg\+xml" href="\/favicon\.svg"(\s*\/)?>/,
    (match, indent) => `${indent}<link rel="icon" href="/favicon.ico" sizes="32x32">\n${match}`
  );
}

// The logo is the first link on every page and its only content is an <img>
// with alt="" (correct - the wordmark next to it is the real label on most
// pages, but on the homepage header the image stands alone). Naming the link
// rather than the image keeps the decorative alt intact.
function fixBrandLink(html) {
  return html.replace(
    /<a class="brand" href="\/"><img class="mark"/g,
    '<a class="brand" href="/" aria-label="Benoit Gaumard - home"><img class="mark"'
  );
}

const results = { analytics: 0, breadcrumb: 0, brand: 0, ico: 0, privacy: 0, skipped: [] };

for (const file of walk(ROOT)) {
  const original = readFileSync(file, "utf8");
  if (!original.includes("news-banner")) continue; // shared shell marks a real page

  let html = original;
  const url = urlFor(file);

  const withGa = injectAnalytics(html);
  if (withGa === null) {
    results.skipped.push(relative(ROOT, file));
  } else if (withGa !== html) {
    results.analytics++;
    html = withGa;
  }

  const withCrumb = injectBreadcrumb(html, url);
  if (withCrumb !== html) {
    results.breadcrumb++;
    html = withCrumb;
  }

  const withBrand = fixBrandLink(html);
  if (withBrand !== html) {
    results.brand++;
    html = withBrand;
  }

  const withIco = addIcoLink(html);
  if (withIco !== html) {
    results.ico++;
    html = withIco;
  }

  const withPrivacy = addFooterLinkStyles(addPrivacyLink(html));
  if (withPrivacy !== html) {
    results.privacy++;
    html = withPrivacy;
  }

  if (html !== original) writeFileSync(file, html, "utf8");
}

console.log(`analytics injected : ${results.analytics} page(s)`);
console.log(`breadcrumb added   : ${results.breadcrumb} page(s)`);
console.log(`brand link labelled: ${results.brand} page(s)`);
console.log(`favicon.ico linked : ${results.ico} page(s)`);
console.log(`privacy link added : ${results.privacy} page(s)`);
if (results.skipped.length) {
  console.log(`\nno anchor found in ${results.skipped.length} file(s):`);
  results.skipped.forEach((f) => console.log(`  - ${f}`));
}
